# Generated by Django 3.1.7 on 2021-02-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210222_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='admission_date',
            field=models.DateField(),
        ),
    ]
